/* Zing Training · 10 daily lessons (ES primary / EN) distilled from the Zing Manual de Limpieza */
window.TRAINING_LAUNCH = "2026-07-29"; // day 1, Miami time
window.LESSONS = [
{ id:"bano", icon:"icons/bathroom.webp",
  t:{es:"Limpieza de Baño — Estándar",en:"Bathroom Clean — Standard"},
  intro:{es:"El baño debe quedar desinfectado, sin cabello, sin manchas y con acabado brillante. El secreto es el orden profesional: pre-tratar primero y el inodoro siempre al final.",en:"The bathroom must be disinfected — no hair, no stains, a polished finish. The secret is professional order: pre-treat first, toilet always last."},
  steps:[
   {es:"Remover alfombras y sacudirlas fuera del baño",en:"Remove rugs and shake them out of the bathroom"},
   {es:"Pre-tratar ducha, tina, lavamanos e inodoro y dejar actuar",en:"Pre-treat shower, tub, sink and toilet — let it work"},
   {es:"Limpiar de arriba hacia abajo, de izquierda a derecha",en:"Clean top to bottom, left to right"},
   {es:"Inodoro al final, con paño exclusivo para el exterior",en:"Toilet last, with a dedicated cloth for the outside"},
   {es:"Barrer y aspirar antes de trapear — nunca omitir",en:"Sweep and vacuum before mopping — never skip"},
   {es:"Revisión final: cabello, espejos, grifería, base del inodoro, piso",en:"Final check: hair, mirrors, faucets, toilet base, floor"}],
  tip:{es:"El cabello en el piso es una de las quejas más comunes. Si al volver a entrar ves algo que limpiar, el baño no estaba terminado.",en:"Hair on the floor is one of the most common complaints. If you re-enter and see something to clean, the bathroom wasn't finished."},
  q:{es:"¿Cuándo se limpia el inodoro?",en:"When do you clean the toilet?",
     opts:[{es:"Primero, para desinfectar temprano",en:"First, to disinfect early"},{es:"Siempre al final, con paño exclusivo",en:"Always last, with a dedicated cloth"},{es:"Después de los espejos",en:"After the mirrors"},{es:"En cualquier momento",en:"Any time"}],
     correct:1,
     why:{es:"El inodoro va siempre al final y su paño nunca toca otras superficies — así evitas contaminación cruzada.",en:"The toilet always goes last and its cloth never touches other surfaces — that prevents cross-contamination."}}},
{ id:"cocina", icon:"icons/countertop.webp",
  t:{es:"Limpieza de Cocina — Estándar",en:"Kitchen Clean — Standard"},
  intro:{es:"La cocina debe quedar desengrasada, sin residuos y con superficies secas y brillantes. La grasa necesita tiempo: pre-tratar es el paso que ahorra más trabajo.",en:"The kitchen must be degreased, residue-free, with dry shiny surfaces. Grease needs time: pre-treating is the step that saves the most work."},
  steps:[
   {es:"Recolectar basura primero y llevarla fuera del área",en:"Collect trash first and take it out of the area"},
   {es:"Pre-tratar estufa, backsplash y zonas con grasa",en:"Pre-treat stove, backsplash and greasy areas"},
   {es:"Trabajar de izquierda a derecha, de arriba hacia abajo",en:"Work left to right, top to bottom"},
   {es:"Limpiar exteriores de electrodomésticos y manijas",en:"Clean appliance exteriors and handles"},
   {es:"Fregadero al final — dejarlo brillante y seco",en:"Sink last — leave it shiny and dry"},
   {es:"Revisar debajo de electrodomésticos pequeños",en:"Check under small appliances"}],
  tip:{es:"Nunca limpies el interior del horno sin autorización — puede causar daños y reclamos.",en:"Never clean the oven interior without authorization — it can cause damage and complaints."},
  q:{es:"¿Por qué pre-tratamos las zonas con grasa?",en:"Why do we pre-treat greasy areas?",
     opts:[{es:"Para que huela mejor",en:"So it smells better"},{es:"El producto afloja la grasa y ahorra tiempo de tallado",en:"The product loosens grease and saves scrubbing time"},{es:"Es opcional si hay prisa",en:"It's optional if in a hurry"},{es:"Para usar más producto",en:"To use more product"}],
     correct:1,
     why:{es:"Si no pre-tratas, tendrás que tallar más fuerte y perderás tiempo. Deja actuar el desengrasante mientras limpias otras áreas.",en:"If you don't pre-treat, you'll scrub harder and lose time. Let the degreaser work while you clean other areas."}}},
{ id:"dusting", icon:"icons/declutter.webp",
  t:{es:"Dusting Completo (High + Low)",en:"Full Dusting (High + Low)"},
  intro:{es:"El polvo siempre cae. Por eso el dusting empieza arriba — esquinas del techo, ventiladores, marcos — y termina en muebles y superficies. Paño con spray ligero, nunca seco.",en:"Dust always falls. That's why dusting starts high — ceiling corners, fans, frames — and ends on furniture and surfaces. Cloth with light spray, never dry."},
  steps:[
   {es:"High dusting primero: techo, ventiladores, rejillas, marcos",en:"High dusting first: ceiling, fans, vents, frames"},
   {es:"Después superficies: perímetro del cuarto, luego el centro",en:"Then surfaces: room perimeter, then the center"},
   {es:"Levantar objetos, limpiar debajo, limpiar el objeto, devolverlo",en:"Lift objects, clean under, clean the object, put it back"},
   {es:"Doblar el paño y usar caras limpias",en:"Fold the cloth and use clean sides"},
   {es:"No limpiar pantallas de TV — solo alrededor",en:"Never wipe TV screens — only around them"}],
  tip:{es:"Limpiar alrededor de objetos sin levantarlos deja marcas visibles de polvo — una causa muy común de quejas.",en:"Cleaning around objects without lifting them leaves visible dust rings — a very common cause of complaints."},
  q:{es:"¿Por qué el high dusting va primero?",en:"Why does high dusting come first?",
     opts:[{es:"Es más difícil y cansa menos al inicio",en:"It's harder and less tiring early"},{es:"El polvo cae — si limpias arriba después, ensucias lo ya limpio",en:"Dust falls — dusting high later dirties what's already clean"},{es:"El duster se seca rápido",en:"The duster dries fast"},{es:"No importa el orden",en:"Order doesn't matter"}],
     correct:1,
     why:{es:"Siempre de arriba hacia abajo: el polvo de las áreas altas cae sobre las superficies, y así solo limpias una vez.",en:"Always top to bottom: dust from high areas falls onto surfaces, so you only clean once."}}},
{ id:"pisos", icon:"icons/floor_magic.webp",
  t:{es:"Vacuum y Mop (Pisos)",en:"Vacuum & Mop (Floors)"},
  intro:{es:"Los pisos se limpian después del dusting, para recoger el polvo que cayó. Regla de oro: nunca trapear un piso que no ha sido aspirado primero.",en:"Floors come after dusting, to pick up what fell. Golden rule: never mop a floor that hasn't been vacuumed first."},
  steps:[
   {es:"Aspirar en líneas rectas, desde el fondo hacia la puerta",en:"Vacuum in straight lines, from the far end toward the door"},
   {es:"No olvidar: bordes, esquinas, debajo de muebles accesibles",en:"Don't forget: edges, corners, under accessible furniture"},
   {es:"Mop húmedo, no empapado — escurrir bien",en:"Mop damp, not soaked — wring it well"},
   {es:"Trapear en “S” hacia la salida, nunca hacia el centro",en:"Mop in an “S” toward the exit, never toward the center"},
   {es:"Cambiar el agua y el mop head cuando estén sucios",en:"Change water and mop head when dirty"}],
  tip:{es:"Un mop demasiado mojado deja manchas, marcas y puede dañar pisos de madera.",en:"An over-wet mop leaves stains, streaks, and can damage wood floors."},
  q:{es:"¿Qué pasa si trapeas sin aspirar primero?",en:"What happens if you mop without vacuuming first?",
     opts:[{es:"El piso queda más brillante",en:"The floor gets shinier"},{es:"Ahorras tiempo",en:"You save time"},{es:"El mop solo empuja polvo, cabello y suciedad",en:"The mop just pushes dust, hair and dirt around"},{es:"Nada, es lo mismo",en:"Nothing, it's the same"}],
     correct:2,
     why:{es:"Es uno de los errores más comunes: sin aspirar, el cabello y la suciedad quedan pegados al piso mojado.",en:"It's one of the most common mistakes: without vacuuming, hair and dirt stick to the wet floor."}}},
{ id:"ventanas", icon:"icons/window.webp",
  t:{es:"Ventanas Interiores",en:"Interior Windows"},
  intro:{es:"El objetivo: vidrio claro, brillante y sin rayas. Primero el polvo, poco producto, y siempre revisar desde diferentes ángulos antes de terminar.",en:"The goal: clear, shiny, streak-free glass. Dust first, minimal product, and always check from different angles before finishing."},
  steps:[
   {es:"Quitar polvo de marcos y vidrio antes de aplicar limpiador",en:"Dust frames and glass before applying cleaner"},
   {es:"Aplicar poco producto — en el paño o ligero sobre el vidrio",en:"Apply little product — on the cloth or lightly on the glass"},
   {es:"Limpiar en movimientos verticales o en “S”",en:"Clean in vertical or “S” motions"},
   {es:"Secar y pulir bordes y esquinas con paño seco",en:"Dry and polish edges and corners with a dry cloth"},
   {es:"Revisar desde varios ángulos — las rayas se esconden",en:"Check from several angles — streaks hide"}],
  tip:{es:"Vidrio con polvo + limpiador = capa de lodo húmedo difícil de remover. Siempre quita el polvo primero.",en:"Dusty glass + cleaner = a wet grime layer that's hard to remove. Always dust first."},
  q:{es:"¿Cuál es el error más común con el limpiador de vidrio?",en:"What's the most common glass-cleaner mistake?",
     opts:[{es:"Usar demasiado producto — deja rayas y manchas",en:"Using too much product — it leaves streaks and marks"},{es:"Usar muy poco",en:"Using too little"},{es:"Aplicarlo en el paño",en:"Applying it to the cloth"},{es:"Limpiar en forma de S",en:"Cleaning in an S pattern"}],
     correct:0,
     why:{es:"Demasiado limpiador crea rayas, manchas y residuos pegajosos. Poca cantidad y buen secado es la fórmula.",en:"Too much cleaner creates streaks, marks and sticky residue. A small amount plus good drying is the formula."}}},
{ id:"horno", icon:"icons/oven.webp",
  t:{es:"Limpieza Profunda de Horno",en:"Deep Clean Oven"},
  intro:{es:"Grasa quemada requiere paciencia, no fuerza: aplicar desengrasante, dejar actuar varios minutos, y nunca tocar resistencias ni componentes eléctricos.",en:"Baked-on grease needs patience, not force: apply degreaser, let it sit several minutes, and never touch heating elements or electrical parts."},
  steps:[
   {es:"Retirar parrillas y bandejas al fregadero",en:"Remove racks and trays to the sink"},
   {es:"Aplicar desengrasante en paredes, base y puerta interior",en:"Apply degreaser to walls, base and inner door"},
   {es:"Dejar actuar varios minutos — no frotar de inmediato",en:"Let it work several minutes — don't scrub right away"},
   {es:"Frotar con esponja; scraper plástico para lo pegado",en:"Scrub with sponge; plastic scraper for stuck bits"},
   {es:"Enjuagar con paño húmedo y secar — evita olores al calentar",en:"Rinse with damp cloth and dry — prevents odors when heated"}],
  tip:{es:"Nunca uses cuchillos ni herramientas metálicas — rayan el horno. Solo scraper plástico.",en:"Never use knives or metal tools — they scratch the oven. Plastic scraper only."},
  q:{es:"¿Dónde NO se aplica el desengrasante?",en:"Where do you NOT apply degreaser?",
     opts:[{es:"Paredes del horno",en:"Oven walls"},{es:"Base del horno",en:"Oven base"},{es:"Resistencias y componentes eléctricos",en:"Heating elements and electrical parts"},{es:"Puerta interior",en:"Inner door"}],
     correct:2,
     why:{es:"Producto en resistencias, ventiladores o componentes eléctricos puede dañar el horno.",en:"Product on heating elements, fans or electrical components can damage the oven."}}},
{ id:"fridge", icon:"icons/fridge.webp",
  t:{es:"Limpieza Profunda de Refrigerador",en:"Fridge Deep Clean"},
  intro:{es:"Higiénico, sin olores y sin cambiar la organización del cliente. Químicos suaves solamente — aquí se guarda comida.",en:"Hygienic, odor-free, and without changing the client's organization. Mild cleaners only — food lives here."},
  steps:[
   {es:"Retirar alimentos al counter; limpiar envases sucios",en:"Move food to the counter; wipe dirty containers"},
   {es:"Retirar bandejas y cajones — lavarlos en el fregadero",en:"Remove shelves and drawers — wash them in the sink"},
   {es:"Limpiar interior con agua tibia y limpiador suave",en:"Clean the interior with warm water and mild cleaner"},
   {es:"Secar TODO antes de reorganizar — evita olores",en:"Dry EVERYTHING before restocking — prevents odors"},
   {es:"Regresar alimentos como estaban organizados",en:"Return food the way it was organized"}],
  tip:{es:"Nunca reorganices por completo los productos del cliente — el refri debe quedar similar a como estaba.",en:"Never fully reorganize the client's products — the fridge should look like it did before."},
  q:{es:"¿Qué producto se usa dentro del refrigerador?",en:"What product goes inside the fridge?",
     opts:[{es:"Desengrasante fuerte",en:"Strong degreaser"},{es:"Cloro sin diluir",en:"Undiluted bleach"},{es:"Limpiador suave o multiuso con agua tibia",en:"Mild or all-purpose cleaner with warm water"},{es:"Limpiador de horno",en:"Oven cleaner"}],
     correct:2,
     why:{es:"Los químicos fuertes pueden contaminar alimentos, dejar olores y dañar superficies.",en:"Strong chemicals can contaminate food, leave odors, and damage surfaces."}}},
{ id:"dishes", icon:"icons/dishes.webp",
  t:{es:"Dish Washing (Lavaplatos + Mano)",en:"Dish Washing (Dishwasher + Hand)"},
  intro:{es:"El lavaplatos primero — es el método más eficiente. A mano solo lo que no cabe o no debe ir: ollas grandes, tablas de madera, cuchillos delicados.",en:"Dishwasher first — it's the most efficient method. Hand-wash only what doesn't fit or shouldn't go in: big pots, wooden boards, delicate knives."},
  steps:[
   {es:"Remover restos de comida antes de cargar",en:"Scrape food scraps before loading"},
   {es:"Rack superior: vasos y tazas · inferior: platos y bowls",en:"Top rack: glasses and cups · bottom: plates and bowls"},
   {es:"No sobrecargar — el agua debe circular",en:"Don't overload — water must circulate"},
   {es:"Iniciar el ciclo; no hace falta esperar a que termine",en:"Start the cycle; no need to wait for it to finish"},
   {es:"Lavar a mano lo demás y dejar el fregadero limpio",en:"Hand-wash the rest and leave the sink clean"}],
  tip:{es:"Las ollas grandes van a mano: en el lavaplatos ocupan demasiado espacio y reducen la eficiencia del ciclo.",en:"Big pots go by hand: in the dishwasher they hog space and reduce cycle efficiency."},
  q:{es:"¿Qué va en el rack superior del lavaplatos?",en:"What goes on the dishwasher's top rack?",
     opts:[{es:"Platos y bowls grandes",en:"Plates and large bowls"},{es:"Vasos, tazas y recipientes pequeños",en:"Glasses, cups and small containers"},{es:"Ollas y sartenes",en:"Pots and pans"},{es:"Tablas de madera",en:"Wooden boards"}],
     correct:1,
     why:{es:"Arriba: vasos, tazas y recipientes pequeños. Abajo: platos, bowls y recipientes grandes.",en:"Top: glasses, cups, small containers. Bottom: plates, bowls, large containers."}}},
{ id:"couch", icon:"icons/couch.webp",
  t:{es:"Couch & Pillow Refresh",en:"Couch & Pillow Refresh"},
  intro:{es:"Un refresh rápido de 2–5 minutos que transforma la sala: aspirar entre cojines, esponjar almohadas y dejar todo alineado y simétrico. Nunca productos líquidos sobre la tela.",en:"A quick 2–5 minute refresh that transforms the living room: vacuum between cushions, fluff pillows, leave everything aligned and symmetric. Never liquid products on fabric."},
  steps:[
   {es:"Retirar throw pillows y cojines a una superficie limpia",en:"Move throw pillows and cushions to a clean surface"},
   {es:"Aspirar asiento, grietas entre cojines y bordes",en:"Vacuum seat, crevices between cushions and edges"},
   {es:"Revisar debajo de cojines: migas, polvo, objetos",en:"Check under cushions: crumbs, dust, small objects"},
   {es:"Sacudir y esponjar cada almohada",en:"Shake and fluff every pillow"},
   {es:"Recolocar todo alineado y simétrico",en:"Put everything back aligned and symmetric"}],
  tip:{es:"Almohadas aplastadas = sofá desordenado, aunque esté limpio. Esponjar siempre.",en:"Flat pillows = a messy-looking couch, even when it's clean. Always fluff."},
  q:{es:"¿Qué NO se debe usar en el sofá?",en:"What should you NOT use on the couch?",
     opts:[{es:"Aspiradora con accesorio de tapicería",en:"Vacuum with upholstery attachment"},{es:"Cepillo suave",en:"Soft brush"},{es:"Sprays o productos líquidos",en:"Sprays or liquid products"},{es:"Paño de microfibra",en:"Microfiber cloth"}],
     correct:2,
     why:{es:"Los líquidos pueden manchar o dañar la tela. Este task es solo refresh en seco.",en:"Liquids can stain or damage the fabric. This task is dry refresh only."}}},
{ id:"laundry", icon:"icons/laundry.webp",
  t:{es:"Laundry: Lavado y Doblado",en:"Laundry: Wash & Fold"},
  intro:{es:"Una carga: revisar bolsillos, no sobrecargar, transferir a la secadora a tiempo. Al doblar: superficie limpia, separar por tipo y un estilo consistente.",en:"One load: check pockets, don't overload, transfer to the dryer on time. When folding: clean surface, sort by type, consistent style."},
  steps:[
   {es:"Revisar bolsillos y objetos sueltos antes de lavar",en:"Check pockets and loose objects before washing"},
   {es:"No sobrecargar — la ropa debe moverse libremente",en:"Don't overload — clothes must move freely"},
   {es:"Detergente del cliente, cantidad recomendada",en:"Client's detergent, recommended amount"},
   {es:"Transferir a la secadora al terminar — ropa húmeda huele mal",en:"Transfer to dryer when done — damp clothes smell"},
   {es:"Doblar sobre superficie limpia, separando por tipo",en:"Fold on a clean surface, sorted by type"}],
  tip:{es:"Doblado inconsistente = pila desordenada. Camisetas con camisetas, pantalones con pantalones.",en:"Inconsistent folding = messy pile. Shirts with shirts, pants with pants."},
  q:{es:"¿Por qué revisamos los bolsillos antes de lavar?",en:"Why do we check pockets before washing?",
     opts:[{es:"Para encontrar propinas",en:"To find tips"},{es:"Objetos olvidados pueden dañar la lavadora o manchar la ropa",en:"Forgotten objects can damage the washer or stain clothes"},{es:"Para contar las prendas",en:"To count the garments"},{es:"No es necesario",en:"It's not necessary"}],
     correct:1,
     why:{es:"Un bolígrafo o unas llaves en un bolsillo pueden arruinar toda la carga y dañar la máquina.",en:"A pen or keys left in a pocket can ruin the whole load and damage the machine."}}}
];
window.TRAINING_NAMES = ["Joceline","Lisa","Daisy","Elizabeth","Haley","Alvaro"];
window.T_UI = {
  es:{day:"Día",lesson:"Lección del día",minutes:"min",start:"Comenzar lección",welcome:"¿Quién está entrenando hoy?",welcomeSub:"Selecciona tu nombre para comenzar",welcomeBack:"¡Bienvenida de vuelta",welcomeBackM:"¡Bienvenido de vuelta",streak:"días seguidos",objective:"Lo esencial",stepsT:"Paso a paso",tipT:"Error común",quizT:"Pregunta del día",check:"Comprobar",correct:"¡Correcto!",incorrect:"No exactamente…",done:"¡Lección completada!",doneSub:"Nos vemos mañana para la siguiente lección.",continueT:"Continuar",completed:"Completada",pending:"Pendiente",today:"Hoy",locked:"Disponible pronto",change:"Cambiar nombre",review:"Repasar lección",another:"Ver otros días",progress:"Tu progreso",back:"Volver"},
  en:{day:"Day",lesson:"Today's lesson",minutes:"min",start:"Start lesson",welcome:"Who's training today?",welcomeSub:"Select your name to begin",welcomeBack:"Welcome back",welcomeBackM:"Welcome back",streak:"day streak",objective:"The essentials",stepsT:"Step by step",tipT:"Common mistake",quizT:"Question of the day",check:"Check",correct:"Correct!",incorrect:"Not quite…",done:"Lesson complete!",doneSub:"See you tomorrow for the next lesson.",continueT:"Continue",completed:"Completed",pending:"Pending",today:"Today",locked:"Available soon",change:"Switch name",review:"Review lesson",another:"See other days",progress:"Your progress",back:"Back"}
};
