/* Zing Onboarding v2 · Paquetes (Parte 2 · Manual de Limpieza)
   Los cuatro paquetes de la app de residentes: Smart Weekly Care, Smart Bi-Weekly Care, Move-in y Move-out.
   Mismo formato que sops.js. Se agregan a window.SOPS y sus preguntas a window.TASK_QUIZ. Cargar después de sops.js y quiz.js. */
(function () {
var P = [
{ id:"pk-weekly", icon:"icons/pkg-weekly.webp", cat:{es:"Paquete",en:"Package"},
  t:{es:"Paquete Smart Weekly Care",en:"Smart Weekly Care package"},
  kw:["paquete","package","semanal","weekly","smart","suscripción","subscription","plan","semana 1","semana 2","week","alternar","alternate","baño","bathroom","refresh"],
  time:{es:"Semanas 1 y 3: limpieza completa (2–3 h según tamaño) · Semanas 2 y 4: solo baños (25–35 min por baño)",en:"Weeks 1 and 3: full clean (2–3 h by size) · Weeks 2 and 4: bathrooms only (25–35 min per bathroom)"},
  goal:{es:"El residente recibe una visita cada semana, alternando: una semana la limpieza completa del apartamento, la siguiente solo los baños. Tú sabes qué semana toca antes de entrar y ejecutas exactamente eso, ni más ni menos.",en:"The resident gets one visit every week, alternating: one week the full apartment clean, the next week bathrooms only. You know which week it is before walking in and do exactly that, no more, no less."},
  tools:{es:["El carrito completo en semanas de limpieza completa","Solo el caddy de baño, aspiradora y mop en semanas de baños","La app: la reserva dice “Full Apartment Reset” o “Bathroom Refresh”"],en:["The full cart on full-clean weeks","Only the bathroom caddy, vacuum and mop on bathroom weeks","The app: the booking says “Full Apartment Reset” or “Bathroom Refresh”"]},
  flow:{es:["Semana 1 · Limpieza completa del apartamento","Semana 2 · Solo baños","Semana 3 · Limpieza completa del apartamento","Semana 4 · Solo baños","El ciclo vuelve a empezar"],en:["Week 1 · Full apartment clean","Week 2 · Bathrooms only","Week 3 · Full apartment clean","Week 4 · Bathrooms only","The cycle starts again"]},
  steps:[
   {t:{es:"Confirmar qué semana es antes de entrar",en:"Confirm which week it is before entering"},d:{es:["Abre la reserva en la app: dice “Full Apartment Reset” o “Bathroom Refresh”.","Si no está claro, escribe a Soporte antes de tocar la puerta. Nunca adivines.","Prepara solo el equipo de esa visita."],en:["Open the booking in the app: it says “Full Apartment Reset” or “Bathroom Refresh”.","If unclear, message Support before knocking. Never guess.","Prepare only the equipment for that visit."]}},
   {t:{es:"Semanas 1 y 3 · Limpieza completa",en:"Weeks 1 and 3 · Full clean"},d:{es:["Ejecuta el flujo completo de la Parte 1: paneo, ejecución por cuartos, cierre y Momento Zing.","Todas las tareas estándar del Manual: baños, cocina, dusting, pisos, ventanas interiores, basura, camas.","Es la visita que devuelve el apartamento a su punto de partida."],en:["Run the full Part 1 flow: scan, room-by-room execution, closing and the Zing Moment.","Every standard Manual task: bathrooms, kitchen, dusting, floors, interior windows, trash, beds.","This is the visit that brings the apartment back to baseline."]}},
   {t:{es:"Semanas 2 y 4 · Solo baños",en:"Weeks 2 and 4 · Bathrooms only"},d:{es:["Todos los baños del apartamento, con el SOP “Limpieza de Baño — Estándar” completo en cada uno.","Incluye piso del baño, espejos, toallas dobladas y basura del baño.","No se limpia cocina, sala ni habitaciones. Si algo está muy sucio afuera, fotografía y avisa; no lo hagas por tu cuenta."],en:["Every bathroom in the apartment, with the full “Bathroom Clean — Standard” SOP in each.","Includes bathroom floor, mirrors, folded towels and bathroom trash.","Kitchen, living room and bedrooms are not cleaned. If something outside is very dirty, photograph and report; don't do it on your own."]}},
   {t:{es:"Cerrar igual en las dos visitas",en:"Close the same way on both visits"},d:{es:["Revisión final, foto, nota de voz si aplica y Momento Zing (toallas en punta, papel doblado) aunque sea semana de baños.","La visita corta también tiene que sentirse Zing."],en:["Final check, photo, voice note if needed and the Zing Moment (towel fold, folded paper) even on bathroom week.","The short visit has to feel Zing too."]}}],
  mistakes:[
   {t:{es:"Hacer limpieza completa en semana de baños",en:"Doing a full clean on bathroom week"},r:{es:"Regalas 2 horas que no están pagadas y te atrasas con la siguiente cita.",en:"You give away 2 unpaid hours and fall behind on the next appointment."}},
   {t:{es:"Hacer solo baños en semana completa",en:"Doing bathrooms only on full-clean week"},r:{es:"El residente pagó la limpieza completa. Es un reclamo seguro.",en:"The resident paid for a full clean. It's a guaranteed complaint."}},
   {t:{es:"Adivinar qué semana toca",en:"Guessing which week it is"},r:{es:"La app lo dice. Si no, Soporte. Nunca la memoria.",en:"The app says it. If not, Support. Never memory."}},
   {t:{es:"Saltarse el Momento Zing en la visita corta",en:"Skipping the Zing Moment on the short visit"},r:{es:"La visita de baños es la que más se nota si se hace sin cuidado.",en:"The bathroom visit is the one that shows most when done carelessly."}}],
  check:{es:["¿Hice exactamente lo que dice la reserva?","Baños: cabello, espejos, grifería, base del inodoro, piso","Toallas y papel con acabado Zing","Foto y cierre en la app"],en:["Did I do exactly what the booking says?","Bathrooms: hair, mirrors, faucet, toilet base, floor","Towels and paper with the Zing finish","Photo and close-out in the app"]},
  scope:{inc:{es:["Semanas 1 y 3: limpieza completa estándar","Semanas 2 y 4: todos los baños, completos"],en:["Weeks 1 and 3: standard full clean","Weeks 2 and 4: every bathroom, in full"]},
         exc:{es:["Horno, refrigerador por dentro, ventanas exteriores, laundry: son extras aparte","Cocina o habitaciones en semana de baños"],en:["Oven, fridge interior, exterior windows, laundry: separate add-ons","Kitchen or bedrooms on bathroom week"]}}},

{ id:"pk-biweekly", icon:"icons/pkg-biweekly.webp", cat:{es:"Paquete",en:"Package"},
  t:{es:"Paquete Smart Bi-Weekly Care",en:"Smart Bi-Weekly Care package"},
  kw:["paquete","package","quincenal","bi-weekly","biweekly","cada dos semanas","every other week","smart","plan","semana 1","semana 3","week 1","week 3","baño","bathroom","refresh"],
  time:{es:"Semana 1: limpieza completa (2–3 h según tamaño) · Semana 3: solo baños (25–35 min por baño). Sin visita en semanas 2 y 4",en:"Week 1: full clean (2–3 h by size) · Week 3: bathrooms only (25–35 min per bathroom). No visit on weeks 2 and 4"},
  goal:{es:"Igual que Smart Weekly pero cada dos semanas: una visita de limpieza completa, dos semanas después una visita de solo baños, y así. El apartamento pasa más tiempo sin servicio, así que la visita completa suele encontrar más acumulado.",en:"Same as Smart Weekly but every other week: one full-clean visit, two weeks later a bathrooms-only visit, and so on. The apartment goes longer without service, so the full visit usually finds more buildup."},
  tools:{es:["El carrito completo en la visita completa","Solo el caddy de baño, aspiradora y mop en la visita de baños","La app: la reserva dice “Full Apartment Reset” o “Bathroom Refresh”"],en:["The full cart on the full visit","Only the bathroom caddy, vacuum and mop on the bathroom visit","The app: the booking says “Full Apartment Reset” or “Bathroom Refresh”"]},
  flow:{es:["Semana 1 · Limpieza completa del apartamento","Semana 2 · Sin visita","Semana 3 · Solo baños","Semana 4 · Sin visita","El ciclo vuelve a empezar"],en:["Week 1 · Full apartment clean","Week 2 · No visit","Week 3 · Bathrooms only","Week 4 · No visit","The cycle starts again"]},
  steps:[
   {t:{es:"Confirmar qué visita es",en:"Confirm which visit it is"},d:{es:["La reserva en la app dice “Full Apartment Reset” o “Bathroom Refresh”.","Como pasan dos semanas entre visitas, es fácil confundirse. La app manda, no la memoria."],en:["The booking in the app says “Full Apartment Reset” or “Bathroom Refresh”.","Two weeks pass between visits, so it's easy to mix up. The app rules, not memory."]}},
   {t:{es:"Visita completa · cuenta con más acumulado",en:"Full visit · expect more buildup"},d:{es:["Dos semanas sin servicio significan más polvo, más cabello, más grasa en la cocina.","Pre-trata baño y cocina apenas entres para que el producto trabaje mientras haces el resto.","Respeta el tiempo de la reserva: si de verdad no alcanza, avisa a Soporte con foto en vez de saltarte tareas en silencio."],en:["Two weeks without service means more dust, more hair, more kitchen grease.","Pre-treat bathroom and kitchen as soon as you walk in so the product works while you do the rest.","Respect the booking time: if it truly isn't enough, message Support with a photo instead of silently skipping tasks."]}},
   {t:{es:"Visita de baños",en:"Bathroom visit"},d:{es:["Todos los baños, SOP completo en cada uno.","Nada fuera del baño. Si el resto está muy sucio, fotografía y avisa: Soporte puede ofrecerle al residente cambiar de plan."],en:["Every bathroom, full SOP in each.","Nothing outside the bathroom. If the rest is very dirty, photograph and report: Support can offer the resident a plan change."]}},
   {t:{es:"Cierre",en:"Close-out"},d:{es:["Revisión final, foto, Momento Zing en las dos visitas."],en:["Final check, photo, Zing Moment on both visits."]}}],
  mistakes:[
   {t:{es:"Confundir la visita por el tiempo que pasó",en:"Mixing up the visit because of the time gap"},r:{es:"Dos semanas borran la memoria. La app dice cuál es.",en:"Two weeks erase memory. The app says which one it is."}},
   {t:{es:"Saltarse tareas en la visita completa porque hay más acumulado",en:"Skipping tasks on the full visit because there's more buildup"},r:{es:"Se avisa a Soporte con foto. Nunca se recorta en silencio.",en:"Message Support with a photo. Never trim silently."}},
   {t:{es:"Tocar la cocina en la visita de baños “porque está muy sucia”",en:"Touching the kitchen on the bathroom visit “because it's so dirty”"},r:{es:"No está pagado y no se espera. Foto y aviso.",en:"Not paid for and not expected. Photo and report."}}],
  check:{es:["¿Hice lo que dice la reserva?","Pre-traté al entrar en la visita completa","Baños completos con acabado Zing","Foto y cierre"],en:["Did I do what the booking says?","Pre-treated on entry on the full visit","Complete bathrooms with the Zing finish","Photo and close-out"]},
  scope:{inc:{es:["Semana 1: limpieza completa estándar","Semana 3: todos los baños, completos"],en:["Week 1: standard full clean","Week 3: every bathroom, in full"]},
         exc:{es:["Visitas en semanas 2 y 4","Extras (horno, refrigerador, ventanas exteriores, laundry)","Cocina o habitaciones en la visita de baños"],en:["Visits on weeks 2 and 4","Add-ons (oven, fridge, exterior windows, laundry)","Kitchen or bedrooms on the bathroom visit"]}}},

{ id:"pk-movein", icon:"icons/pkg-movein.webp", cat:{es:"Paquete",en:"Package"},
  t:{es:"Move-in Cleaning (apartamento vacío, antes de mudarse)",en:"Move-in Cleaning (empty apartment, before moving in)"},
  kw:["move in","move-in","mudanza","entrada","apartamento vacío","empty","nuevo residente","new resident","gabinetes","cabinets","cajones","drawers","closets","baseboards","zócalos","electrodomésticos","appliances","polvo de construcción","construction dust"],
  time:{es:"3–5 h según tamaño. Es la visita más larga del catálogo junto con Move-out",en:"3–5 h by size. The longest visit in the catalog along with Move-out"},
  goal:{es:"El residente entra a un apartamento que se siente nuevo: sin polvo de obra ni del inquilino anterior, gabinetes y cajones limpios por dentro, electrodomésticos listos para usar, closets, zócalos y cada esquina. Va más allá de la limpieza completa porque el apartamento está vacío y se puede llegar a todo.",en:"The resident walks into an apartment that feels new: no construction or previous-tenant dust, cabinets and drawers clean inside, appliances ready to use, closets, baseboards and every corner. It goes beyond the full clean because the apartment is empty and everything is reachable."},
  tools:{es:["Carrito completo","Escalera pequeña","Aspiradora con boquilla plana y cepillo redondo","Desengrasante, Easy-Off, producto de acero inoxidable","Paños extra: el polvo fino satura rápido","Bolsas de basura grandes"],en:["Full cart","Small ladder","Vacuum with crevice tool and round brush","Degreaser, Easy-Off, stainless steel product","Extra cloths: fine dust saturates them fast","Large trash bags"]},
  flow:{es:["Paneo y fotos de cómo llegó","High dusting de todo el apartamento","Cocina por dentro y por fuera","Baños completos","Closets, gabinetes y cajones por dentro","Ventanas interiores, puertas, marcos, zócalos, interruptores","Pisos al final: aspirar y trapear todo","Revisión con luz y fotos finales"],en:["Scan and arrival photos","High dusting throughout","Kitchen inside and out","Full bathrooms","Closets, cabinets and drawers inside","Interior windows, doors, frames, baseboards, switches","Floors last: vacuum and mop everything","Check with light and final photos"]},
  steps:[
   {t:{es:"Paneo y fotos",en:"Scan and photos"},d:{es:["Recorre todo el apartamento antes de empezar. Fotografía daños, manchas o cosas dejadas por el inquilino anterior.","Si hay basura o muebles abandonados, avisa a Soporte antes de mover nada."],en:["Walk the whole apartment before starting. Photograph damage, stains or items left by the previous tenant.","If there's trash or abandoned furniture, message Support before moving anything."]}},
   {t:{es:"High dusting completo",en:"Full high dusting"},d:{es:["Techos, esquinas, ventiladores, lámparas, rejillas de aire, parte alta de gabinetes, puertas y marcos.","El polvo de obra es fino y cae: siempre antes de limpiar cualquier superficie baja."],en:["Ceilings, corners, fans, light fixtures, vents, tops of cabinets, doors and frames.","Construction dust is fine and falls: always before any lower surface."]}},
   {t:{es:"Cocina por dentro",en:"Kitchen inside"},d:{es:["Gabinetes y cajones vacíos: aspirar el polvo, luego paño húmedo por dentro, secar.","Horno por dentro (SOP Horno), refrigerador por dentro (SOP Refrigerador), microondas, lavavajillas: filtro y empaque.","Debajo y detrás de los electrodomésticos si se pueden mover con seguridad.","Fregadero, grifería y drenaje desinfectados."],en:["Empty cabinets and drawers: vacuum dust, then damp cloth inside, dry.","Oven inside (Oven SOP), fridge inside (Fridge SOP), microwave, dishwasher: filter and gasket.","Under and behind appliances if they can be moved safely.","Sink, faucet and drain disinfected."]}},
   {t:{es:"Baños completos",en:"Full bathrooms"},d:{es:["SOP de baño completo, más: gabinetes y cajones por dentro, botiquín, rejilla del extractor, detrás del inodoro.","Sarro de inquilinos anteriores en ducha y grifería: usar Zep Shower Tub & Tile si la superficie lo permite."],en:["Full bathroom SOP, plus: cabinets and drawers inside, medicine cabinet, vent cover, behind the toilet.","Previous-tenant limescale on shower and faucet: use Zep Shower Tub & Tile if the surface allows."]}},
   {t:{es:"Closets, puertas, zócalos, interruptores",en:"Closets, doors, baseboards, switches"},d:{es:["Closets: repisas, barras y piso por dentro.","Todas las puertas, marcos, manijas, interruptores y enchufes (rociar el paño).","Zócalos de todo el apartamento con paño húmedo."],en:["Closets: shelves, rods and floor inside.","Every door, frame, handle, switch and outlet (spray the cloth).","Baseboards throughout with a damp cloth."]}},
   {t:{es:"Pisos y cierre",en:"Floors and close-out"},d:{es:["Aspirar todo, incluidas esquinas y closets. Trapear con el producto correcto para el piso.","Revisar con la luz de la ventana en ángulo: el polvo fino se ve así.","Fotos finales de cada cuarto. Este es el primer contacto del residente con Zing."],en:["Vacuum everything including corners and closets. Mop with the right product for the floor.","Check with window light at an angle: fine dust shows that way.","Final photos of every room. This is the resident's first contact with Zing."]}}],
  mistakes:[
   {t:{es:"Tratarlo como una limpieza completa normal",en:"Treating it like a normal full clean"},r:{es:"El residente pagó por dentro de gabinetes, closets y electrodomésticos. Es lo que diferencia el paquete.",en:"The resident paid for inside cabinets, closets and appliances. That's what sets the package apart."}},
   {t:{es:"Limpiar abajo antes de arriba",en:"Cleaning low before high"},r:{es:"El polvo de obra cae y hay que repetir.",en:"Construction dust falls and you redo it."}},
   {t:{es:"No fotografiar daños al llegar",en:"Not photographing damage on arrival"},r:{es:"Después parece que fue Zing.",en:"Later it looks like Zing did it."}},
   {t:{es:"Usar los mismos paños para todo",en:"Using the same cloths for everything"},r:{es:"El polvo fino los satura. Cambia seguido o solo lo mueves de lugar.",en:"Fine dust saturates them. Change often or you just move it around."}}],
  check:{es:["Gabinetes y cajones limpios por dentro","Horno, refrigerador y microondas por dentro","Closets vacíos y limpios","Zócalos, interruptores, marcos","Sin polvo en la luz de la ventana","Fotos de llegada y de cierre"],en:["Cabinets and drawers clean inside","Oven, fridge and microwave inside","Closets empty and clean","Baseboards, switches, frames","No dust in the window light","Arrival and close-out photos"]},
  scope:{inc:{es:["Todo lo de la limpieza completa","Interior de gabinetes, cajones y closets","Interior de horno, refrigerador, microondas y lavavajillas","Zócalos, puertas, marcos, interruptores","Detrás y debajo de electrodomésticos si se pueden mover"],en:["Everything in the full clean","Inside cabinets, drawers and closets","Inside oven, fridge, microwave and dishwasher","Baseboards, doors, frames, switches","Behind and under appliances if movable"]},
         exc:{es:["Ventanas exteriores y balcón a presión","Paredes completas o pintura","Alfombras con shampoo","Retirar muebles o basura pesada del inquilino anterior"],en:["Exterior windows and pressure-washing the balcony","Full walls or paint","Carpet shampoo","Removing furniture or heavy trash left by the previous tenant"]}}},

{ id:"pk-moveout", icon:"icons/pkg-moveout.webp", cat:{es:"Paquete",en:"Package"},
  t:{es:"Move-out Cleaning (apartamento vacío, al salir)",en:"Move-out Cleaning (empty apartment, at move-out)"},
  kw:["move out","move-out","mudanza","salida","entrega","depósito","deposit","inspección","inspection","apartamento vacío","empty","gabinetes","cabinets","cajones","drawers","closets","zócalos","baseboards","electrodomésticos","appliances","marcas en la pared","wall marks"],
  time:{es:"3–5 h según tamaño y estado. Suele encontrar más suciedad que Move-in",en:"3–5 h by size and condition. Usually finds more dirt than Move-in"},
  goal:{es:"El apartamento queda listo para la inspección del edificio y para el siguiente residente: sin rastro de quien vivió ahí. Mismo alcance que Move-in, con más atención a lo que deja el uso: grasa en la cocina, sarro en el baño, marcas en paredes y zócalos, huecos detrás de los muebles.",en:"The apartment is ready for the building's inspection and the next resident: no trace of who lived there. Same scope as Move-in, with more attention to what use leaves behind: kitchen grease, bathroom limescale, marks on walls and baseboards, the spots behind furniture."},
  tools:{es:["Carrito completo","Escalera pequeña","Aspiradora con accesorios","Desengrasante, Easy-Off, Zep Shower Tub & Tile, esponja mágica","Paños extra y bolsas de basura grandes"],en:["Full cart","Small ladder","Vacuum with attachments","Degreaser, Easy-Off, Zep Shower Tub & Tile, magic eraser","Extra cloths and large trash bags"]},
  flow:{es:["Paneo y fotos de cómo llegó","Retirar basura y objetos olvidados (con aviso)","High dusting","Cocina profunda por dentro y por fuera","Baños profundos","Closets, gabinetes, cajones","Paredes: marcas puntuales; zócalos, puertas, interruptores","Pisos al final","Revisión como inspector y fotos finales"],en:["Scan and arrival photos","Remove trash and forgotten items (with notice)","High dusting","Deep kitchen inside and out","Deep bathrooms","Closets, cabinets, drawers","Walls: spot marks; baseboards, doors, switches","Floors last","Inspect like an inspector and final photos"]},
  steps:[
   {t:{es:"Paneo, fotos y lo que quedó",en:"Scan, photos and what was left"},d:{es:["Fotografía cada cuarto como llegó: manchas, huecos en la pared, daños. Protege a Zing y al residente.","Objetos olvidados: no los tires. Foto y aviso a Soporte; ellos confirman con el residente.","Basura suelta sí se retira."],en:["Photograph every room as found: stains, wall holes, damage. Protects Zing and the resident.","Forgotten items: don't throw them out. Photo and message Support; they confirm with the resident.","Loose trash does get removed."]}},
   {t:{es:"High dusting y luego cocina profunda",en:"High dusting, then deep kitchen"},d:{es:["High dusting de todo el apartamento primero.","Cocina: desengrasar campana, estufa, backsplash, frente y lados de gabinetes. Horno por dentro con Easy-Off. Refrigerador por dentro y, si se puede, por detrás.","Gabinetes y cajones por dentro: migas, manchas de líquidos, papel de repisa si lo dejaron.","Lavavajillas: filtro, empaque, ciclo corto vacío si hay tiempo."],en:["High dusting throughout first.","Kitchen: degrease hood, stove, backsplash, cabinet fronts and sides. Oven inside with Easy-Off. Fridge inside and, if possible, behind.","Cabinets and drawers inside: crumbs, liquid stains, shelf paper if left.","Dishwasher: filter, gasket, a short empty cycle if time allows."]}},
   {t:{es:"Baños profundos",en:"Deep bathrooms"},d:{es:["SOP de baño completo más sarro: Zep Shower Tub & Tile en ducha, grifería (si no es dorada) y puertas de vidrio.","Moho en juntas: Scrubbing Bubbles, y si no sale, Tilex. Enjuague completo entre productos.","Gabinetes, cajones, botiquín y rejilla del extractor por dentro."],en:["Full bathroom SOP plus limescale: Zep Shower Tub & Tile on shower, faucet (if not gold) and glass doors.","Mold in grout: Scrubbing Bubbles, and Tilex if it persists. Full rinse between products.","Cabinets, drawers, medicine cabinet and vent cover inside."]}},
   {t:{es:"Paredes, zócalos, puertas, closets",en:"Walls, baseboards, doors, closets"},d:{es:["Marcas puntuales en paredes mate con esponja mágica húmeda, solo la marca. Prueba en una esquina; en pintura brillante no.","Huecos de clavos y rayones: no se reparan, se fotografían.","Zócalos con paño húmedo en todo el apartamento. Puertas, marcos, manijas, interruptores, enchufes.","Closets por dentro: repisas, barras, piso, puertas."],en:["Spot marks on matte walls with a damp magic eraser, only the mark. Test a corner; not on glossy paint.","Nail holes and scratches: not repaired, photographed.","Baseboards with a damp cloth throughout. Doors, frames, handles, switches, outlets.","Closets inside: shelves, rods, floor, doors."]}},
   {t:{es:"Pisos y revisión como inspector",en:"Floors and inspector check"},d:{es:["Aspirar todo, esquinas, closets, detrás de puertas. Trapear con el producto correcto.","Recorre el apartamento como si fueras el administrador que va a devolver el depósito: abre cada gabinete, cada cajón, cada closet; mira el horno y el refrigerador por dentro.","Fotos finales de cada cuarto, gabinetes abiertos y electrodomésticos abiertos."],en:["Vacuum everything, corners, closets, behind doors. Mop with the right product.","Walk the apartment as if you were the manager returning the deposit: open every cabinet, drawer and closet; look inside the oven and fridge.","Final photos of every room, cabinets open, appliances open."]}}],
  mistakes:[
   {t:{es:"Tirar cosas que el residente olvidó",en:"Throwing out things the resident forgot"},r:{es:"Foto y aviso a Soporte. Solo basura evidente se retira.",en:"Photo and message Support. Only obvious trash gets removed."}},
   {t:{es:"No fotografiar daños al llegar",en:"Not photographing damage on arrival"},r:{es:"En un move-out, el edificio revisa. Lo que no fotografiaste puede terminar siendo culpa de Zing.",en:"On a move-out, the building inspects. What you didn't photograph can end up blamed on Zing."}},
   {t:{es:"Frotar toda la pared con esponja mágica",en:"Scrubbing the whole wall with a magic eraser"},r:{es:"Deja parches de brillo. Solo la marca, y nunca en pintura brillante.",en:"Leaves shiny patches. Only the mark, never on glossy paint."}},
   {t:{es:"Dejar el horno o el refrigerador sin abrir",en:"Leaving the oven or fridge unopened"},r:{es:"Es lo primero que abre el inspector.",en:"It's the first thing the inspector opens."}}],
  check:{es:["Cada gabinete, cajón y closet abierto y limpio","Horno y refrigerador limpios por dentro","Sin grasa en campana ni backsplash","Sin sarro ni moho en la ducha","Zócalos y marcas de pared atendidos","Fotos de llegada, de daños y de cierre"],en:["Every cabinet, drawer and closet opened and clean","Oven and fridge clean inside","No grease on hood or backsplash","No limescale or mold in the shower","Baseboards and wall marks handled","Arrival, damage and close-out photos"]},
  scope:{inc:{es:["Todo lo de Move-in","Desengrasado profundo de cocina","Sarro y moho de baño","Marcas puntuales en paredes","Retiro de basura suelta"],en:["Everything in Move-in","Deep kitchen degreasing","Bathroom limescale and mold","Spot wall marks","Loose trash removal"]},
         exc:{es:["Reparar huecos, pintura o daños","Retirar muebles o electrodomésticos","Alfombras con shampoo","Ventanas exteriores","Decidir qué objetos olvidados se tiran: eso lo confirma Soporte"],en:["Repairing holes, paint or damage","Removing furniture or appliances","Carpet shampoo","Exterior windows","Deciding which forgotten items to discard: Support confirms that"]}}}
];
var Q = {
 "pk-weekly":[
  {q:"Llegas a un Smart Weekly. ¿Cómo sabes si toca limpieza completa o solo baños?", opts:["Por lo que recuerdo de la semana pasada","La reserva en la app lo dice; si no, pregunto a Soporte","Le pregunto al residente"], a:1,
   why:"La app manda. Ni la memoria ni el residente deciden el alcance de la visita."},
  {q:"Es semana de baños y la cocina está sucia. ¿Qué haces?", opts:["Limpio la cocina rápido","Solo baños; fotografío la cocina y aviso a Soporte","Hago limpieza completa"], a:1,
   why:"La visita corta es solo baños. Lo demás se reporta, no se regala."},
  {q:"¿Qué se hace igual en las dos visitas del paquete?", opts:["Nada, son visitas distintas","Revisión final, foto y Momento Zing","Trapear todo el apartamento"], a:1,
   why:"La visita corta también tiene que sentirse Zing: cierre y detalle siempre."}],
 "pk-biweekly":[
  {q:"¿En qué se diferencia Smart Bi-Weekly de Smart Weekly?", opts:["Solo hay visitas de baños","Mismo ciclo, pero una visita cada dos semanas","Es limpieza completa siempre"], a:1,
   why:"Semana 1 completa, semana 3 baños, sin visita en las semanas 2 y 4."},
  {q:"En la visita completa hay mucho más acumulado de lo normal y el tiempo no alcanza. ¿Qué haces?", opts:["Me salto el dusting y no digo nada","Aviso a Soporte con foto antes de recortar tareas","Cobro más al residente"], a:1,
   why:"Nunca se recorta en silencio. Soporte decide con el residente."},
  {q:"¿Qué haces apenas entras en la visita completa de un Bi-Weekly?", opts:["Empiezo por la sala","Pre-trato baño y cocina para que el producto trabaje mientras hago el resto","Aspiro todo primero"], a:1,
   why:"Dos semanas sin servicio piden pre-tratamiento inmediato."}],
 "pk-movein":[
  {q:"¿Qué diferencia un Move-in de una limpieza completa normal?", opts:["Es más rápido porque está vacío","Incluye interior de gabinetes, cajones, closets y electrodomésticos","Solo se limpian pisos y baños"], a:1,
   why:"El apartamento vacío permite llegar a lo que la limpieza normal no toca. Eso es lo que se paga."},
  {q:"¿Por dónde empiezas un Move-in con polvo de obra?", opts:["Por los pisos","Por el high dusting: techos, ventiladores, alto de gabinetes","Por los gabinetes por dentro"], a:1,
   why:"El polvo fino cae. Arriba primero o repites todo."},
  {q:"Encuentras muebles abandonados del inquilino anterior. ¿Qué haces?", opts:["Los saco al pasillo","Foto y aviso a Soporte antes de mover nada","Los limpio y los dejo"], a:1,
   why:"Retirar muebles no está en el alcance y puede ser del edificio. Soporte decide."}],
 "pk-moveout":[
  {q:"Hay una caja con ropa que el residente dejó. ¿Qué haces?", opts:["La tiro, es un move-out","Foto y aviso a Soporte; ellos confirman con el residente","Me la llevo"], a:1,
   why:"Solo basura evidente se retira. Un objeto olvidado lo confirma Soporte."},
  {q:"¿Cómo revisas el apartamento antes de cerrar un Move-out?", opts:["Una mirada general desde la puerta","Como el inspector: abro cada gabinete, cajón, closet, horno y refrigerador","Solo reviso los baños"], a:1,
   why:"El edificio va a abrir todo. Tú lo abres primero."},
  {q:"Hay marcas en una pared mate. ¿Cómo las atiendes?", opts:["Esponja mágica húmeda solo en la marca, probando antes en una esquina","Frotar toda la pared para que quede uniforme","Clorox Clean-Up"], a:0,
   why:"Solo la marca. Toda la pared deja parches de brillo, y el cloro mancha la pintura."}]
};
window.SOPS = window.SOPS.concat(P);
window.TASK_QUIZ = Object.assign(window.TASK_QUIZ || {}, Q);
window.PACKAGE_SOPS = P;
})();
